# Generated by Django 4.1 on 2023-02-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('job', models.CharField(max_length=25, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ot', models.CharField(max_length=10, unique=True, verbose_name='OT')),
                ('cod_sap', models.CharField(max_length=10, unique=True, verbose_name='CODIGO_SAP')),
                ('description', models.CharField(max_length=300, verbose_name='Descripcción')),
                ('location', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('start', models.DateTimeField(verbose_name='Inicio')),
                ('completed', models.DateTimeField(verbose_name='Finalizado')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ot', to='users.user')),
            ],
        ),
    ]
